### create users
POST http://localhost:3333/users
Content-Type: application/json

{
	"name": "Angela",
	"email": "angela@proton.me",
	"password": "101010"
}

### authenticate sessions (credentials)
POST http://localhost:3333/sessions
Content-Type: application/json

{
	"email": "angela@proton.me",
	"password": "101010"
}	

###

GET http://localhost:3333/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMzEwYmVmZS00NDNkLTQxNWUtOWQ0Mi00MzlhYzM5Y2Q4ZmYiLCJpYXQiOjE2OTYxNzIwNzJ9.ywMi6M-Z_SN-r02gNcF7h_xMxMJZ6LWovv39My_WxpY

