### create users
POST http://localhost:3333/users
Content-Type: application/json

{
	"name": "Angela",
	"email": "angela@proton.me",
	"password": "101010"
}

### authenticate sessions (credentials)
POST http://localhost:3333/sessions
Content-Type: application/json

{
	"email": "angela@proton.me",
	"password": "101010"
}	

###
